apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-4-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm-4-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sm-4-app
    spec:
      containers:
        - name: simple-memorizer-4
          image: gcr.io/project/image
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: sm-4-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: sm-4-app
